### ISSUE TITLE
Change the default Compile Root SDK to iOS instead of macOS?

### ISSUE THREAD

**Issue by zwang** [NeoTeo/SwiftGMP#13]
Hi Teo,

Do you think it is OK to change the default Compile Root SDK to iOS instead of macOS?

By changing to iOS, the enable-bitCode is then by default enabled. 

If it is macOS, then the generated framework (carthage build for iOS) will cause the app using it unable to enable bitcode. 

I can send a pull request if you think I can do it. 

Thanks,
Zhao

**Comment by NeoTeo** [comment]
Hi zwang. Thanks for using SwiftGMP. 
I'm not sure changing the default is the solution. These kinds of settings should be set by the Carthage (or other build tools) based on what you're building. 

Also, have you checked that the problem you're having with uploading the app to the app store isn't due to the bitcode being enabled? I'm having to disable it when uploading (other projects unrelated to SwiftGMP) or it will hang.

**Comment by zwang** [comment]
Yeah, you are right, I changed at my local, still didn't solve the problem I mentioned in #12 until I uncheck "Including Bitcode".  Thanks for the help. 👍
